// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pycfkcndaqkquzbksckj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5Y2ZrY25kYXFrcXV6YmtzY2tqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTI1NTYsImV4cCI6MjA1OTc4ODU1Nn0.H6lDgLkpbLVZgq5HEHSfenL3096kVjV_UOm1GfMn6do";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);