
// This file is automatically generated. Do not edit it directly.
import { dynamicSupabase } from './dynamic-client';

// Re-export the dynamic supabase client
export const supabase = dynamicSupabase.getClient();

// For backward compatibility, also export the dynamic instance
export { dynamicSupabase };
