
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://siwtzurwqvlalpljwalk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpd3R6dXJ3cXZsYWxwbGp3YWxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNjUyNzAsImV4cCI6MjA2NDg0MTI3MH0.34ihbpBYE-Uedm81nuhCZp-1ZMOx7SNcRp5JZiUh1rI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
